apiVersion: v1
kind: ConfigMap
metadata:
  name: git-config
  namespace: user1-devspaces
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /etc/
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
data:
  gitconfig: |
    [user]
      email = user1@redhat.com
      name = user1
    [alias]
      st = status
      co = checkout
      ci = commit