apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: user1-devspaces
  annotations:
    controller.devfile.io/mount-path: /tmp/.git-credentials/
  labels:
    controller.devfile.io/git-credential: "true"
    controller.devfile.io/watch-secret: "true"
type: Opaque
stringData:
  credentials: https://user1:openshift@gitea-gitea.${SUB_DOMAIN}