---
apiVersion: v1
kind: Namespace
metadata:
  name: user1-devspaces
  annotations:
    openshift.io/description: "Devspaces Namespace"
    openshift.io/display-name: "Devspaces Namespace"
    che.eclipse.org/username: user1-devspaces
    openshift.io/requester: 'system:serviceaccount:openshift-operators:che'
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    app.kubernetes.io/component: workspaces-namespace
    app.kubernetes.io/part-of: che.eclipse.org
    kubernetes.io/metadata.name: user1-devspaces