apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: web
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: coolstore
      kind: TriggerBinding
    template:
      ref: web
