apiVersion: batch/v1
kind: Job
metadata:
  name: configure-quay
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:1.0
          envFrom:
          - secretRef:
              name: api-token
          env:
          - name: sub_domain
            value: ${SUB_DOMAIN}
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              echo "Setup temporary OCP user to make ansible happy"

              echo "tempuser:x:$(id -u):$(id -g):,,,:${HOME}:/bin/bash" >> /etc/passwd
              echo "tempuser:x:$(id -G | cut -d' ' -f 2)" >> /etc/group
              id

              git clone https://github.com/coolstore-demo/quay-init

              cd quay-init

              ansible-galaxy collection install -r collections/requirements.yaml

              ansible-playbook quay-configure.yaml -e access_token=$token -e sub_domain=$sub_domain

          name: configure-quay
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: default
      serviceAccountName: default