apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coolstore-devs-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: coolstore-devs