apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-pipeline
  generateName: post-sync-pipeline-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - image: registry.access.redhat.com/ubi8
          command:
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "Content-Type: application/json"
          - "--data"
          - "{}"
          - "--connect-timeout"
          - "60"
          - "https://el-route-inventory-prod-coolstore-cicd.apps.rhte.0x74.p1.openshiftapps.com/"
          imagePullPolicy: Always
          name: post-sync-pipeline
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
