---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quay
spec:
  params:
    - name: name
    - name: repository
    - name: namespace
    - name: docker_url
    - name: homepage
    - name: updated_tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: create-pull-request
        generateName: quay-webhook-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: create-pull-request
        params:
          - name: MANIFESTS_GIT_BRANCH
            value: main
          - name: MANIFESTS_GIT_REPO
            value: 'https://github.com/coolstore-demo/coolstore'
          - name: IMAGE
            value: $(params.docker_url)
          - name: IMAGE_TAG
            value: $(params.updated_tag)
          - name: APPLICATION_NAME
            value: $(params.name)
          - name: SONARQUBE_HOST
            value: sonarqube-dev-tools.apps.rhte.0x74.p1.openshiftapps.com
        workspaces:
          - name: gitops-manifests
            persistentVolumeClaim:
              claimName: gitops-manifests
          - name: acs-central
            secret:
              secretName: acs-central