apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gateway
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: coolstore
    template:
      ref: gateway
