apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gateway
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: gateway-pipeline-
        labels:
          tekton.dev/pipeline: gateway-pipeline
      spec:
        params:
          - name: GIT_REPO
            value: $(tt.params.git-repo-url)
          - name: GIT_BRANCH
            value: $(tt.params.git-revision)
        pipelineRef:
          name: gateway-pipeline
        workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: gateway-pvc
        - name: maven-settings
          emptyDir: {}
